services:
  - type: web
    name: vgmf-fellowship-portal
    runtime: node
    plan: free
    region: oregon
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npx prisma db push && npm run db:seed-cms && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: ZEPTOMAIL_TOKEN
        sync: false
      - key: ZEPTOMAIL_FROM_EMAIL
        sync: false
      - key: ZEPTOMAIL_FROM_NAME
        value: VGMF Fellowship Portal
      - key: ZEPTOMAIL_API_URL
        value: https://api.zeptomail.in/v1.1/email
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_OTP_TEMPLATE_NAME
        value: authentication
      - key: WHATSAPP_OTP_TEMPLATE_LANGUAGE
        value: en
